name: Build

on:
  push:
    branches-ignore:
      # We ignore on push to release because the Deliver workflow builds and
      # uploads, while this just builds.
      - 'release/**'
  pull_request:
    branches:
      # Only trigger on pull request to develop, since this is the primary branch of
      # integration for both internal and external contributions.
      - 'develop'

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install automake and pkg-config libtool
      run: brew install automake pkg-config go-task/tap/go-task libtool
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Build libtesseract
      run: task build-tesseract-xcframework
