name: Deliver

on:
  push:
    tags:
      - '*'

jobs:
  deliver:
    runs-on: macOS-latest
    if: "!contains(github.event.head_commit.message, 'Do not upload')"
    steps:
      - uses: actions/checkout@v1
      - name: Install automake and pkg-config libtool
        run: brew install automake pkg-config go-task/tap/go-task libtool
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Assign Tag Number to RELEASE_VERSION environment variable
        run: |
          echo "RELEASE_VERSION=${{  github.ref_name }}" >> $GITHUB_ENV
          echo $GITHUB_ENV
      - name: Build libtesseract
        run: task build-tesseract-xcframework-zip
      - name: Update Package.swift
        run: python3 update_package_swift.py --version $RELEASE_VERSION
      - name: Commit Package.swift update
        uses: EndBug/add-and-commit@v4
        with:
          add: 'Package.swift'
          message: 'Auto-updating Package.swift'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create draft release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "libtesseract-${{ env.RELEASE_VERSION }}.xcframework.zip"
          draft: true
          allowUpdates: true
          tag: ${{ env.RELEASE_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}